# Build and push artifacts
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 13
        platform: x64
    - name: Configure G++ version
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 10
        sudo update-alternatives --set gcc "/usr/bin/gcc-13"
        sudo update-alternatives --set g++ "/usr/bin/g++-13"
    - name: CMake generate
      env:
        ARTIFACT_NAME: mrst-${{ runner.os }}
      run: |
        cmake -B build \
          -DCMAKE_INSTALL_PREFIX=$ARTIFACT_NAME \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=OFF \
      shell: bash
    - name: Build
      run: cmake --build build --target install -j
    
    - uses: actions/upload-artifact@v3
      if: github.ref == 'refs/heads/main' && github.repository == 'em-eight/mrst'
      with:
        name: mrst-${{ runner.os }}
        path: mrst-${{ runner.os }}